services:
  - type: web
    name: job-queue-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install --include=dev && npm run build
    startCommand: node dist/src/main.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://mini-job-queue-dasboard.vercel.app,http://localhost:5173,http://127.0.0.1:5173
      - key: DATABASE_URL
        fromDatabase:
          name: job-queue-db
          property: connectionString

databases:
  - name: job-queue-db
    plan: free
    databaseName: jobqueue
    user: jobqueue_user
